import type { NavItem } from '@/features/navigation/nav-button'
import {
  IconBell,
  IconBellFilled,
  IconBook,
  IconBookFilled,
  IconCashBanknote,
  IconCashBanknoteFilled,
  IconClipboardList,
  IconClipboardListFilled,
  IconGraph,
  IconGraphFilled,
  IconHome,
  IconHomeFilled,
  IconPencil,
  IconUser,
  IconUserCog,
  IconUserFilled,
  IconWriting,
} from '@tabler/icons-react'

export const studentLinks: NavItem[] = [
  {
    link: '/dashboard',
    label: 'Dashboard',
    Icon: IconHomeFilled,
    IconInactive: IconHome,
    fuzzy: true,
  },
  {
    link: '/courses',
    label: 'Courses',
    Icon: IconBookFilled,
    IconInactive: IconBook,
    fuzzy: true,
  },
  {
    link: '/enrollment',
    label: 'Enrollment',
    Icon: IconClipboardListFilled,
    IconInactive: IconClipboardList,
    fuzzy: true,
  },
  {
    link: '/billing',
    label: 'Billing',
    Icon: IconCashBanknoteFilled,
    IconInactive: IconCashBanknote,
    fuzzy: true,
  },
  {
    link: '/notifications',
    label: 'Notifications',
    Icon: IconBellFilled,
    IconInactive: IconBell,
    fuzzy: true,
  },
  {
    link: '/profile',
    label: 'Profile',
    Icon: IconUserFilled,
    IconInactive: IconUser,
    fuzzy: true,
  },
]

export const adminLinks: NavItem[] = [
  {
    link: '/dashboard',
    label: 'Dashboard',
    Icon: IconGraphFilled,
    IconInactive: IconGraph,
    fuzzy: true,
  },
  {
    link: '/courses',
    label: 'Courses',
    Icon: IconBookFilled,
    IconInactive: IconBook,
    fuzzy: true,
  },
  {
    link: '/users',
    label: 'Users',
    Icon: IconUserCog,
    IconInactive: IconUserCog,
    fuzzy: true,
  },
  {
    link: '/enrollment',
    label: 'Enrollment',
    Icon: IconClipboardListFilled,
    IconInactive: IconClipboardList,
    fuzzy: true,
  },
  {
    link: '/billing',
    label: 'Billing',
    Icon: IconCashBanknoteFilled,
    IconInactive: IconCashBanknote,
    fuzzy: true,
  },
  {
    link: '/profile',
    label: 'Profile',
    Icon: IconUserFilled,
    IconInactive: IconUser,
    fuzzy: true,
  },
  {
    link: '/cms',
    label: 'CMS',
    Icon: IconWriting,
    IconInactive: IconPencil,
    fuzzy: true,
  },
]
