// This file is auto-generated by @hey-api/openapi-ts

export type Role = 'student' | 'mentor' | 'admin';

export type UserCredentialsDto = {
    email: string;
    password: string;
};

export type CreateUserWithAccountDto = {
    firstName: string;
    middleName?: string | null;
    lastName: string;
    role: Role;
    credentials?: UserCredentialsDto;
};

export type User = {
    id: string;
    firstName: string;
    middleName: string | null;
    lastName: string;
    role: Role;
    createdAt: string;
    updatedAt: string;
    deletedAt: string | null;
};

export type UpdateUserDto = {
    [key: string]: unknown;
};

export type CreateCourseDto = {
    [key: string]: unknown;
};

export type UpdateCourseDto = {
    [key: string]: unknown;
};

export type UsersControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type UsersControllerFindAllResponses = {
    200: string;
};

export type UsersControllerFindAllResponse = UsersControllerFindAllResponses[keyof UsersControllerFindAllResponses];

export type UsersControllerCreateData = {
    body: CreateUserWithAccountDto;
    path?: never;
    query?: never;
    url: '/users';
};

export type UsersControllerCreateErrors = {
    /**
     * Failed to create user
     */
    500: unknown;
};

export type UsersControllerCreateResponses = {
    201: User;
};

export type UsersControllerCreateResponse = UsersControllerCreateResponses[keyof UsersControllerCreateResponses];

export type UsersControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersControllerRemoveResponses = {
    200: string;
};

export type UsersControllerRemoveResponse = UsersControllerRemoveResponses[keyof UsersControllerRemoveResponses];

export type UsersControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersControllerFindOneResponses = {
    200: string;
};

export type UsersControllerFindOneResponse = UsersControllerFindOneResponses[keyof UsersControllerFindOneResponses];

export type UsersControllerUpdateData = {
    body: UpdateUserDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersControllerUpdateResponses = {
    200: string;
};

export type UsersControllerUpdateResponse = UsersControllerUpdateResponses[keyof UsersControllerUpdateResponses];

export type CoursesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/courses';
};

export type CoursesControllerFindAllResponses = {
    200: string;
};

export type CoursesControllerFindAllResponse = CoursesControllerFindAllResponses[keyof CoursesControllerFindAllResponses];

export type CoursesControllerCreateData = {
    body: CreateCourseDto;
    path?: never;
    query?: never;
    url: '/courses';
};

export type CoursesControllerCreateResponses = {
    201: string;
};

export type CoursesControllerCreateResponse = CoursesControllerCreateResponses[keyof CoursesControllerCreateResponses];

export type CoursesControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/courses/{id}';
};

export type CoursesControllerRemoveResponses = {
    200: string;
};

export type CoursesControllerRemoveResponse = CoursesControllerRemoveResponses[keyof CoursesControllerRemoveResponses];

export type CoursesControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/courses/{id}';
};

export type CoursesControllerFindOneResponses = {
    200: string;
};

export type CoursesControllerFindOneResponse = CoursesControllerFindOneResponses[keyof CoursesControllerFindOneResponses];

export type CoursesControllerUpdateData = {
    body: UpdateCourseDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/courses/{id}';
};

export type CoursesControllerUpdateResponses = {
    200: string;
};

export type CoursesControllerUpdateResponse = CoursesControllerUpdateResponses[keyof CoursesControllerUpdateResponses];

export type TestControllerTestStudentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/test/student';
};

export type TestControllerTestStudentResponses = {
    200: string;
};

export type TestControllerTestStudentResponse = TestControllerTestStudentResponses[keyof TestControllerTestStudentResponses];

export type TestControllerTestAdminData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/test/admin';
};

export type TestControllerTestAdminResponses = {
    200: string;
};

export type TestControllerTestAdminResponse = TestControllerTestAdminResponses[keyof TestControllerTestAdminResponses];

export type ClientOptions = {
    baseUrl: string;
};