# .woodpecker.yml
pipeline:
  type-check-frontend:
    image: node:20
    environment:
      # pnpm setup needs to install globally first
      PATH: /root/.local/share/pnpm:$PATH
    commands:
      - corepack enable
      - corepack prepare pnpm@latest --activate
      - cd frontend
      - pnpm install --no-frozen-lockfile
      - pnpm tsc --noEmit
    when:
      event: pull_request
      branch:
        - main
        - develop

  type-check-backend:
    image: node:20
    environment:
      PATH: /root/.local/share/pnpm:$PATH
      DATABASE_CLOUD_URL: ${DATABASE_CLOUD_URL}
      DIRECT_CLOUD_URL: ${DIRECT_CLOUD_URL}
    commands:
      - corepack enable
      - corepack prepare pnpm@latest --activate
      - cd backend
      - pnpm install --no-frozen-lockfile
      - pnpm prisma-gen
      - pnpm prisma-gen-sql
      - pnpm tsc --noEmit
    when:
      event: pull_request
      branch:
        - main
        - develop
