name: PR Type Checking (Frontend & Backend)

on:
  push:
    branches:
      - "feat/cap-101"
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  type-check-frontend:
    name: Frontend Type Checking
    timeout-minutes: 5
    runs-on: self-hosted

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Install pnpm Package Manager
        uses: pnpm/action-setup@v4

      - name: Set up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Restore pnpm Cache and Node Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: pnpm install --no-frozen-lockfile

      - name: Run TypeScript Type Check
        working-directory: ./frontend
        run: pnpm tsc --noEmit

  type-check-backend:
    name: Backend Type Checking
    timeout-minutes: 5
    runs-on: self-hosted
    env:
      DATABASE_CLOUD_URL: ${{ secrets.DATABASE_CLOUD_URL }}
      DIRECT_CLOUD_URL: ${{ secrets.DIRECT_CLOUD_URL }}

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Install pnpm Package Manager
        uses: pnpm/action-setup@v4

      - name: Set up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Restore pnpm Cache and Node Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            backend/node_modules
          key: ${{ runner.os }}-backend-${{ hashFiles('backend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-backend-

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: pnpm install --no-frozen-lockfile

      - name: Generate Prisma Types
        working-directory: ./backend
        run: pnpm prisma-gen

      - name: Generate Prisma SQL Types
        working-directory: ./backend
        run: pnpm prisma-gen-sql

      - name: Run TypeScript Type Check
        working-directory: ./backend
        run: pnpm tsc --noEmit
