name: MMDC Student Portal Actions

on:
  push:
    branches:
      - main
      - develop
      - feat/cap-60
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Code Quality Checks
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Restore frontend dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: pnpm install --no-frozen-lockfile

      - name: Type check frontend code
        working-directory: ./frontend
        run: pnpm tsc --noEmit
